require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WindGeneratorsController do

  # This should return the minimal set of attributes required to create a valid
  # WindGenerator. As you add validations to WindGenerator, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WindGeneratorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wind_generators as @wind_generators" do
      wind_generator = WindGenerator.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wind_generators).should eq([wind_generator])
    end
  end

  describe "GET show" do
    it "assigns the requested wind_generator as @wind_generator" do
      wind_generator = WindGenerator.create! valid_attributes
      get :show, {:id => wind_generator.to_param}, valid_session
      assigns(:wind_generator).should eq(wind_generator)
    end
  end

  describe "GET new" do
    it "assigns a new wind_generator as @wind_generator" do
      get :new, {}, valid_session
      assigns(:wind_generator).should be_a_new(WindGenerator)
    end
  end

  describe "GET edit" do
    it "assigns the requested wind_generator as @wind_generator" do
      wind_generator = WindGenerator.create! valid_attributes
      get :edit, {:id => wind_generator.to_param}, valid_session
      assigns(:wind_generator).should eq(wind_generator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WindGenerator" do
        expect {
          post :create, {:wind_generator => valid_attributes}, valid_session
        }.to change(WindGenerator, :count).by(1)
      end

      it "assigns a newly created wind_generator as @wind_generator" do
        post :create, {:wind_generator => valid_attributes}, valid_session
        assigns(:wind_generator).should be_a(WindGenerator)
        assigns(:wind_generator).should be_persisted
      end

      it "redirects to the created wind_generator" do
        post :create, {:wind_generator => valid_attributes}, valid_session
        response.should redirect_to(WindGenerator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wind_generator as @wind_generator" do
        # Trigger the behavior that occurs when invalid params are submitted
        WindGenerator.any_instance.stub(:save).and_return(false)
        post :create, {:wind_generator => {}}, valid_session
        assigns(:wind_generator).should be_a_new(WindGenerator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WindGenerator.any_instance.stub(:save).and_return(false)
        post :create, {:wind_generator => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wind_generator" do
        wind_generator = WindGenerator.create! valid_attributes
        # Assuming there are no other wind_generators in the database, this
        # specifies that the WindGenerator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WindGenerator.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => wind_generator.to_param, :wind_generator => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested wind_generator as @wind_generator" do
        wind_generator = WindGenerator.create! valid_attributes
        put :update, {:id => wind_generator.to_param, :wind_generator => valid_attributes}, valid_session
        assigns(:wind_generator).should eq(wind_generator)
      end

      it "redirects to the wind_generator" do
        wind_generator = WindGenerator.create! valid_attributes
        put :update, {:id => wind_generator.to_param, :wind_generator => valid_attributes}, valid_session
        response.should redirect_to(wind_generator)
      end
    end

    describe "with invalid params" do
      it "assigns the wind_generator as @wind_generator" do
        wind_generator = WindGenerator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WindGenerator.any_instance.stub(:save).and_return(false)
        put :update, {:id => wind_generator.to_param, :wind_generator => {}}, valid_session
        assigns(:wind_generator).should eq(wind_generator)
      end

      it "re-renders the 'edit' template" do
        wind_generator = WindGenerator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WindGenerator.any_instance.stub(:save).and_return(false)
        put :update, {:id => wind_generator.to_param, :wind_generator => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wind_generator" do
      wind_generator = WindGenerator.create! valid_attributes
      expect {
        delete :destroy, {:id => wind_generator.to_param}, valid_session
      }.to change(WindGenerator, :count).by(-1)
    end

    it "redirects to the wind_generators list" do
      wind_generator = WindGenerator.create! valid_attributes
      delete :destroy, {:id => wind_generator.to_param}, valid_session
      response.should redirect_to(wind_generators_url)
    end
  end

end
